require:
  - rubocop-rspec
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/*'
Style/MethodCallWithArgsParentheses:
  Enabled: true
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/**/*.rb'
Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods
  Categories:
     association:
       - has_many
       - has_one
       - belongs_to
     attribute_macros:
       - attr_accessor
       - attr_reader
       - attr_writer
     macros:
       - validates
       - validate
     module_inclusion:
       - include
       - prepend
       - extend
