---
swagger: '2.0'
info:
  title: API V1
  version: v1
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    name: X-Api-Key
    in: header
definitions:
  Movie:
    type: object
    properties:
      title:
        type: string
      year:
        type: string
      rated:
        type: string
      released:
        type: string
      runtime:
        type: string
      genre:
        type: string
      director:
        type: string
      writer:
        type: string
      actors:
        type: string
      plot:
        type: string
      language:
        type: string
      country:
        type: string
      awards:
        type: string
      poster:
        type: string
      ratings:
        type: object
      metascore:
        type: string
      imdb_rating:
        type: string
      imdb_votes:
        type: string
      imdb_id:
        type: string
      dvd:
        type: string
      box_office:
        type: string
      production:
        type: string
      website:
        type: string
      response:
        type: string
      runtime_seconds:
        type: integer
  Price:
    type: object
    properties:
      value:
        type: string
      description:
        type: string
  Showing:
    type: object
    properties:
      movie_id:
        type: integer
      price_id:
        type: integer
      start:
        type: string
      finish:
        type: string
paths:
  "/movies":
    get:
      summary: List movies
      tags:
      - Movies
      produces:
      - application/json
      responses:
        '200':
          description: Movie list
          schema:
            type: array
            items:
              "$ref": "#/definitions/Movie"
  "/movies/{id}":
    get:
      summary: Get movie
      tags:
      - Movies
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: Movie result
          schema:
            "$ref": "#/definitions/Movie"
  "/movies/{id}/review/{rating}":
    post:
      summary: Review movie
      tags:
      - Movies
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      - name: rating
        in: path
        type: integer
        required: true
      responses:
        '204':
          description: Rating success
  "/prices":
    get:
      summary: List prices
      tags:
      - Prices
      produces:
      - application/json
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Prices list
          schema:
            type: array
            items:
              "$ref": "#/definitions/Price"
    post:
      summary: Create price
      tags:
      - Prices
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: price
        in: body
        schema:
          type: object
          properties:
            value:
              type: string
            description:
              type: string
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          description: Price result
          schema:
            type: object
            properties:
              value:
                type: string
              description:
                type: string
        '422':
          description: Price result
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
              status:
                type: string
  "/prices/{id}":
    get:
      summary: Get price
      tags:
      - Prices
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Price result
          schema:
            "$ref": "#/definitions/Price"
    patch:
      summary: Update price
      tags:
      - Prices
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: price
        in: body
        schema:
          type: object
          properties:
            value:
              type: string
            description:
              type: string
        required: true
      - name: id
        in: path
        type: integer
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Price result
          schema:
            "$ref": "#/definitions/Price"
    delete:
      summary: Delete price
      security:
      - ApiKeyAuth: []
      tags:
      - Prices
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '204':
          description: Price result
  "/showings":
    get:
      summary: List showings
      tags:
      - Showings
      produces:
      - application/json
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Showing list
          schema:
            type: array
            items:
              "$ref": "#/definitions/Showing"
    post:
      summary: Create showing
      tags:
      - Showings
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: showing
        in: body
        schema:
          type: object
          properties:
            movie_id:
              type: integer
            price_id:
              type: integer
            start:
              type: string
            finish:
              type: string
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          description: Showing result
          schema:
            type: object
            properties:
              movie_id:
                type: integer
              price_id:
                type: integer
              start:
                type: string
              finish:
                type: string
        '422':
          description: Showing result
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
              status:
                type: string
  "/showings/{id}":
    get:
      summary: Get showing
      tags:
      - Showings
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Showing result
          schema:
            "$ref": "#/definitions/Showing"
    patch:
      summary: Update showing
      tags:
      - Showings
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: showing
        in: body
        schema:
          type: object
          properties:
            movie_id:
              type: integer
            price_id:
              type: integer
            start:
              type: string
            finish:
              type: string
        required: true
      - name: id
        in: path
        type: integer
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Showing result
          schema:
            "$ref": "#/definitions/Showing"
    delete:
      summary: Delete showing
      security:
      - ApiKeyAuth: []
      tags:
      - Showings
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '204':
          description: Showing result
