name: Rails Lint and Spec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0

      - name: Initialize database
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          bundle exec rails db:create

      - name: Run specs
        run: |
          bundle exec rails spec
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAILS_ENV: test

      - name: Report coverage
        run: |
           bash <(curl -Ls https://coverage.codacy.com/get.sh) report --api-token "$env:CODACY_API_TOKEN" --organization-provider gh --username aladac --project-name fast_cinema
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
    services:
      postgres:
        image: postgres:11.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0
      - name: Run linters
        run: |
          bundle exec rubocop --config .rubocop.yml
